export const CONTEXT_SIZE = 32768
export const SUMMARIZE_CONTEXT_SIZE = 4096
export const MAX_CONCURRENT_AGENTS = 2
export const CONTEXT_CHAR_THRESHOLD = Math.floor(CONTEXT_SIZE * 3.5 * 0.6)
export const CONTEXT_KEEP_RECENT_CHARS = Math.floor(CONTEXT_CHAR_THRESHOLD * 0.5)
